const esc=v=>String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const short=v=>v?String(v).slice(0,10):'—';
const pair=(version,sha)=>version?`${esc(version)} @ ${esc(short(sha))}`:esc(short(sha));
const num=(p,k)=>esc(p[k]??0);
async function run(){
 const r=await fetch('../portfolio/status/index.json'); const d=await r.json(); document.getElementById('meta').textContent=`Control plane ${d.CONTROL_PLANE_VERSION} • generated ${d.GENERATED_AT||'not yet'}`;
 const metrics=['TOTAL_PROJECTS','TOTAL_REQUIREMENTS','FEATURES_IMPLEMENTED_NOT_CONNECTED','FEATURES_CUSTOMER_READY','FEATURES_RELEASED','INTEGRATION_GAPS','FALSE_DONE_FEATURES','UNREACHABLE_SCREENS','BACKEND_ONLY_FEATURES','UI_ONLY_FEATURES','MISSING_BINDINGS'];
 document.getElementById('cards').innerHTML=metrics.map(k=>`<div class="card"><div>${k.replaceAll('_',' ')}</div><div class="n">${d[k]??0}</div></div>`).join('');
 document.getElementById('rows').innerHTML=(d.PROJECTS||[]).map(p=>`<tr><td>${esc(p.PROJECT_ID)}</td><td>${esc(p.HEALTH)}</td><td>${pair(p.CURRENT_PRODUCTION_VERSION,p.PRODUCTION_SHA)}</td><td>${pair(p.CURRENT_DEVELOPMENT_VERSION||p.TARGET_DEVELOPMENT_VERSION,p.CANONICAL_INTEGRATION_SHA)}</td><td>${num(p,'FEATURES_CUSTOMER_READY')}</td><td>${num(p,'INTEGRATION_GAPS')}</td><td>${num(p,'FALSE_DONE_FEATURES')}</td><td>${num(p,'UNREACHABLE_SCREENS')}</td><td>${num(p,'BACKEND_ONLY_FEATURES')}</td><td>${num(p,'UI_ONLY_FEATURES')}</td><td>${num(p,'MISSING_BINDINGS')}</td><td>${esc(p.CONTROL_PLANE_VERSION)}</td></tr>`).join('');
 document.getElementById('project-details').innerHTML=(d.PROJECTS||[]).map(p=>`<section class="project"><h2>${esc(p.DISPLAY_NAME||p.PROJECT_ID)}</h2><div class="grid"><div><h3>REQUIREMENTS</h3><b>${num(p,'TOTAL_REQUIREMENTS')}</b></div><div><h3>FEATURES</h3>Planned ${num(p,'FEATURES_PLANNED')} • Partial ${num(p,'FEATURES_PARTIAL')} • Implemented Not Connected ${num(p,'FEATURES_IMPLEMENTED_NOT_CONNECTED')} • E2E ${num(p,'FEATURES_END_TO_END_WORKING')} • QA ${num(p,'FEATURES_QA_VERIFIED')} • Customer Ready ${num(p,'FEATURES_CUSTOMER_READY')} • Released ${num(p,'FEATURES_RELEASED')}</div><div><h3>SCREENS</h3>Total ${num(p,'SCREENS_TOTAL')} • Visual Complete ${num(p,'SCREENS_VISUAL_COMPLETE')} • Functional Complete ${num(p,'SCREENS_FUNCTIONAL_COMPLETE')} • Customer Ready ${num(p,'SCREENS_CUSTOMER_READY')}</div><div><h3>INTEGRATION GAPS</h3>Total ${num(p,'INTEGRATION_GAPS')} • Unreachable ${num(p,'UNREACHABLE_SCREENS')} • Backend-only ${num(p,'BACKEND_ONLY_FEATURES')} • UI-only ${num(p,'UI_ONLY_FEATURES')} • Missing bindings ${num(p,'MISSING_BINDINGS')} • False done ${num(p,'FALSE_DONE_FEATURES')}</div><div><h3>CUSTOMER READY</h3>${(p.CUSTOMER_READY_FEATURE_IDS||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join('')||'—'}</div></div><p>Code ${esc(p.CODE_COMPLETION)}% • Connectivity ${esc(p.CONNECTIVITY_COMPLETION)}% • QA ${esc(p.QA_COMPLETION)}% • Customer Ready ${esc(p.CUSTOMER_READY_COMPLETION)}% • Release ${esc(p.RELEASE_COMPLETION)}%</p></section>`).join('');
}
run().catch(e=>document.getElementById('meta').textContent='Dashboard data unavailable: '+e.message);
